version: 2.1
jobs:
  build:
    resource_class: medium
    docker:
      # https://github.com/CircleCI-Public/cimg-go
      - image: cimg/go:1.19

    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "~/go/pkg/mod"
      - run:
          name: Run tests
          command: go test -v
      - run:
          name: Run tests
          command: echo $CC_TEST_REPORTER_ID
